# Generated by Django 4.2.27 on 2025-12-18 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwimCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='수모 상품명', max_length=255)),
                ('image', models.ImageField(help_text='수모 사진', upload_to='swimcaps/')),
                ('purchase_link', models.URLField(help_text='구매 링크')),
                ('brand', models.CharField(help_text='브랜드명', max_length=255)),
                ('price', models.IntegerField(help_text='가격')),
                ('dominant_color_hex', models.CharField(blank=True, help_text='지배색', max_length=7)),
                ('palette', models.JSONField(blank=True, default=list, help_text='팔레트')),
                ('dominant_lab', models.JSONField(blank=True, help_text='Lab 색공간 좌표', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='DB에 저장된 시간')),
            ],
        ),
        migrations.CreateModel(
            name='Swimsuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='수영복 상품명 (예: Nike 경기용 수영복)', max_length=255)),
                ('image', models.ImageField(help_text='수영복 사진', upload_to='swimsuits/')),
                ('purchase_link', models.URLField(help_text='구매 링크 (쇼핑몰 URL)')),
                ('brand', models.CharField(help_text='브랜드명 (예: Nike, Speedo)', max_length=255)),
                ('price', models.IntegerField(help_text='가격 (예: 89000.00)')),
                ('dominant_color_hex', models.CharField(blank=True, help_text='지배색(대표 색상) — HEX 형식 (예: #FF0000)', max_length=7)),
                ('palette', models.JSONField(blank=True, default=list, help_text="팔레트(추출된 색상 목록) — JSON 형식 (예: ['#FF0000', '#FFFFFF'])")),
                ('dominant_lab', models.JSONField(blank=True, help_text='Lab 색공간 좌표 — JSON 형식 (예: [50.0, 60.0, 30.0])', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='DB에 저장된 시간 (자동 기록)')),
            ],
        ),
    ]
