# Generated by Django 4.2.27 on 2025-12-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swimsuit',
            old_name='purchase_link',
            new_name='product_url',
        ),
    ]
