# Generated by Django 4.2.27 on 2025-12-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_purchase_link_swimsuit_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swimcap',
            old_name='purchase_link',
            new_name='product_url',
        ),
        migrations.AlterField(
            model_name='swimcap',
            name='created_at',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True), help_text='DB에 저장된 시간'),
        ),
        migrations.AlterField(
            model_name='swimsuit',
            name='created_at',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True), help_text='DB에 저장된 시간 (자동 기록)'),
        ),
    ]
