# Generated by Django 4.2.27 on 2025-12-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_purchase_link_swimcap_product_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimcap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='DB에 저장된 시간'),
        ),
        migrations.AlterField(
            model_name='swimsuit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='DB에 저장된 시간 (자동 기록)'),
        ),
    ]
