# Generated by Django 4.2.27 on 2025-12-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_swimcap_created_at_alter_swimsuit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimsuit',
            name='price',
            field=models.IntegerField(help_text='가격 (예: 89000)'),
        ),
    ]
